name: common
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=3.2.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: 1.0.8
  get_it: ^8.0.3
  path_provider: 2.1.5
  flutter_bloc: 9.1.0
  bloc: 9.0.0
  equatable: 2.0.7
  intl: 0.19.0
  rxdart: 0.28.0
  stream_transform: 2.1.1
  go_router: 14.8.1
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: 5.0.0
  build_runner: 2.4.14
  dart_code_metrics_presets: 2.21.0
flutter:
  generate: true
  uses-material-design: true