name: example
description: A new Flutter application.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.6.2

dependencies:
  auth:
    path: modules/auth
  home:
    path: modules/home
  common:
    path: modules/common
  more:
    path: modules/more
  account_details:
    path: modules/account_details
  navigation_observer:
    path: modules/navigation_observer
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: ^6.1.4
  auto_route: ^10.0.1
  get_it: ^8.0.3

dev_dependencies:
  build_runner: ^2.4.15
  auto_route_generator: ^10.0.1

flutter:
  uses-material-design: true
