name: navigation_observer
description: base classes for observing navigation events
version: 1.0.0
homepage: none
publish_to: none

environment:
  sdk: ">=3.2.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  equatable: ^2.0.7
  auto_route: ^10.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
